from .DataPrepUtils import FashionMNIST_DataPrep
from .DimReductionUtils import plot_2PC,plot_3PC,plot_Spectrum_and_CVR
from .ClusteringUtils import plot_clusters_composition,plot_SankeyDiagram
from .EvaluationUtils import plot_ConfusionMatrix
